EMPTY = 0
RUN_LVL = 1
BOOT_TIME = 2
NEW_TIME = 3
OLD_TIME = 4
INIT_PROCESS = 5
LOGIN_PROCESS = 6
USER_PROCESS = 7
DEAD_PROCESS = 8
ACCOUNTING = 9
UT_UNKNOWN = 0

UT_LINESIZE = 32
UT_NAMESIZE = 32
UT_HOSTSIZE = 256
UT_IDSIZE = 4

UTMP_FILE = "/var/run/utmp"
WTMP_FILE = "/var/log/wtmp"
